name: "CI"

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
      - name: Format the code
        run: npm run format
  release:
    needs: [build]
    # if: ${{github.event.}}
    uses: pradeept/gh-release-workflow/.github/workflows/release.yaml@main
       
