name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    # permissions: 
        # contents: write
        
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Bump the version
        run: npm version from-git
