name: Release

on:
  workflow_call: 
    inputs:
      version:
        type: string
        description: "Version type"
        required: true
    

jobs:
  release:
    permissions:
      contents: write

    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT_TOKEN}}
      - name: Configure name and email
        run: |
          git config user.name ${{secrets.GITHUB_USER}}
          git config user.email ${{secrets.GITHUB_EMAIL}}
          
      - name: Bump the version
        run: |
          npm version ${{inputs.version}} -m "chore: release v%s"
      - name: Sync repo code
        run: |
          git push origin main --follow-tags
          